server:
  port: 10086
spring:
  application:
    name: cornucopia-eureka-server
eureka:
  client:
    # 不在页面上显示当前 服务
    fetch-registry: false
    # 不拉取服务列表
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 5000 # 每隔5秒进行一次服务列表清理